from selenium.webdriver.common.by import By

class Locators:    
    nickname = (By.XPATH, '//div[@class="columnSmall"]')
    photo = (By.XPATH, '//button[@class="circleSmall"]')
    log_in = (By.XPATH, '//button[text()="Вход и регистрация"]')
    no_account = (By.XPATH, '//button[text()="Нет аккаунта"]')
    email_create_acc = (By.XPATH, '//input[@name="email"]')
    password_create_acc = (By.XPATH, '//input[@name="password"]')
    submit_password_create_acc = (By.XPATH, '//input[@name="submitPassword"]')
    create_acc_button = (By.XPATH, '//button[text()="Создать аккаунт"]')
    user_info = (By.XPATH, '//div[@class="header_flexRow__Xdqv1"]')
    email_field = (By.XPATH, '//div[@class="input_inputError__fLUP9"]')
    email_error = (By.XPATH, '//input[@placeholder="Введите Email"]')    
    password_error = (By.XPATH, '//input[@placeholder="Пароль"]')
    submit_password_error = (By.XPATH, '//input[@placeholder="Повторите пароль"]')
    error = (By.XPATH, '//span[text()="Ошибка"]')    
    email_login = (By.XPATH, '//input[@name="email"]')
    password_login = (By.XPATH, '//input[@name="password"]')
    enter = (By.XPATH, '//button[text()="Войти"]')
    exit = (By.XPATH, '//button[text()="Выйти"]')    
    create_card = (By.XPATH, '//button[text()="Разместить объявление"]')
    must_auth = (By.XPATH, '//h1[text()= "Чтобы разместить объявление, авторизуйтесь"]')
    card_name = (By.XPATH, '//input[@placeholder="Название"]')
    card_description = (By.XPATH, '//textarea[@placeholder="Описание товара"]')
    card_cost = (By.XPATH, '//input[@placeholder="Стоимость"]')
    card_dropdown_button_1 = (By.XPATH, '//div[@class="createListing_inputRow__fmwXw"]/div[@class= "dropDownMenu_dropMenu__sBxhz"]/div/button[@class= "dropDownMenu_arrowDown__pfGL1 dropDownMenu_noDefault__wSKsP"]')
    card_dropdown_1 = (By.XPATH, '//button/span[text()= "Садоводство"]')
    card_dropdown_button_2 = (By.XPATH, '//form[@class="createListing_shell__A5EA7"]/div[@class= "dropDownMenu_dropMenu__sBxhz"]/div/button[@class= "dropDownMenu_arrowDown__pfGL1 dropDownMenu_noDefault__wSKsP"]')    
    card_dropdown_2 = (By.XPATH, '//button/span[text()= "Казань"]')
    item_status_BU = (By.XPATH, '//div[@class="createListing_inputRadio__ApFGD"]/div[2]/div')
    public_button = (By.XPATH, '//button[text()= "Опубликовать"]')
    apply_button = (By.XPATH, '//button[text()= "Применить"]')
    my_card_img = (By.XPATH, '//img[@alt= "Плюшевые котики"]')


