from imports import *

class Locators:    
    nickname = (By.XPATH, '//div[@class="columnSmall"]')
    photo = (By.XPATH, '//button[@class="circleSmall"]')
    log_in = (By.XPATH, '//button[text()="Вход и регистрация"]')
    no_account = (By.XPATH, '//button[text()="Нет аккаунта"]')
    email_create_acc = (By.XPATH, '//div[@class="popUp_inputColumn__RgD8n"]/div/div/div/input[@name="email"]')
    password_create_acc = (By.XPATH, '//div[@class="popUp_inputColumn__RgD8n"]/div/div/div/input[@name="password"]')
    submit_password_create_acc = (By.XPATH, '//div[@class="popUp_inputColumn__RgD8n"]/div/div/div/input[@name="submitPassword"]')
    create_acc_button = (By.XPATH, '//div[@class="popUp_buttonRow__+W8JD"]/button[text()="Создать аккаунт"]')
    user_info = (By.XPATH, '//div[@class="header_flexRow__Xdqv1"]')
    email_field = (By.XPATH, '//div[@class="input_inputError__fLUP9"]')
    email_error = (By.XPATH, '//div[@class="popUp_inputColumn__RgD8n"]/div[1]/div/div')
    password_error = (By.XPATH, '//div[@class="popUp_inputColumn__RgD8n"]/div[2]/div/div')
    submit_password_error = (By.XPATH, '//div[@class="popUp_inputColumn__RgD8n"]/div[3]/div/div')
    error = (By.XPATH, '//span[text()="Ошибка"]')    
    email_login = (By.XPATH, '//div[@class="input_inputDefault__UmPK0"]/input[@name="email"]')
    password_login = (By.XPATH, '//div[@class="input_inputDefault__UmPK0"]/input[@name="password"]')
    enter = (By.XPATH, '//button[text()="Войти"]')
    exit = (By.XPATH, '//div[@class="columnSmall"]/button[text()="Выйти"]')    
    create_card = (By.XPATH, '//button[text()="Разместить объявление"]')
    must_auth = (By.XPATH, '//h1[text()= "Чтобы разместить объявление, авторизуйтесь"]')
    card_name = (By.XPATH, '//input[@placeholder="Название"]')
    card_description = (By.XPATH, '//textarea[@placeholder="Описание товара"]')
    card_cost = (By.XPATH, '//input[@placeholder="Стоимость"]')
    card_dropdown_button_1 = (By.XPATH, '//div/div[2]/div/form/div[2]/div[2]/div[1]/button')
    card_dropdown_1 = (By.XPATH, '//div[@class="dropDownMenu_options__CmHmm"]/button[3]')
    card_dropdown_button_2 = (By.XPATH, '//div/div[2]/div/form/div[3]/div[1]/button')
    card_dropdown_2 = (By.XPATH, '//div/div[2]/div/form/div[3]/div[2]/button[6]')
    item_status_BU = (By.XPATH, '//div/div[2]/div/form/fieldset/div/div[2]/div')
    public_button = (By.XPATH, '//button[text()= "Опубликовать"]')
    apply_button = (By.XPATH, '//div/div[2]/form/div[2]/button')
    my_card_img = (By.XPATH, '//img[@alt= "Плюшевые котики"]')


